sf_front:
    resource: '@SfFrontBundle/Resources/config/routing.yml'
    prefix:   /

sf_admin:
    resource: '@SfAdminBundle/Resources/config/routing.yml'
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"