sf_front:
    resource: "@SfFrontBundle/Controller/"
    type:     annotation
    prefix:   /

sf_core:
    resource: "@SfCoreBundle/Controller/"
    type:     annotation
    prefix:   /

sf_admin:
    resource: "@SfAdminBundle/Controller/"
    type:     annotation
    prefix:   /
